workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Generar carpetas de la plataforma
        script: |
          flutter create --platforms=android .
      - name: Activar desugaring en Android
        script: |
          sed -i '' 's/compileOptions {/compileOptions {\n        coreLibraryDesugaringEnabled = true/' android/app/build.gradle.kts
          echo "" >> android/app/build.gradle.kts
          echo "dependencies {" >> android/app/build.gradle.kts
          echo "    coreLibraryDesugaring(\"com.android.tools:desugar_jdk_libs:2.0.4\")" >> android/app/build.gradle.kts
          echo "}" >> android/app/build.gradle.kts
      - name: Descargar dependencias
        script: |
          flutter pub get
      - name: Compilar APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
